/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces_graficas.abm_producto;

import interfaces_graficas.menus.MenuAdministrador;
import logica.managers.ManagerProducto;
import objects.Producto;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;

/**
 *
 * @author tovib
 */
public class ABM_Producto extends javax.swing.JFrame {

    /**
     * Creates new form abm_producto
     */
    private static HashMap<String, Producto> listaProductos = new HashMap<>();
    private DefaultTableModel model;
    private String user;
    
    public ABM_Producto(String user) {
        initComponents();
        this.user = user;
        listaProductos = ManagerProducto.getHashMapAllProductos();
        updateTabla(listaProductos);
        cambiar_visibilidad_producto.setEnabled(false);
        modificar_producto.setEnabled(false);
        addList();
    }
    
    public void disableButtons() {
        agregar_producto.setEnabled(false);
        boton_salir.setEnabled(false);
        modificar_producto.setEnabled(false);
        cambiar_visibilidad_producto.setEnabled(false);
    }
    
    public void enabledButtons() {
        agregar_producto.setEnabled(true);
        boton_salir.setEnabled(true);
        modificar_producto.setEnabled(true);
        cambiar_visibilidad_producto.setEnabled(false);
        modificar_producto.setEnabled(false);
        
         
    }
    
    public void updateProductos () {
        listaProductos = ManagerProducto.getHashMapAllProductos();
        updateTabla(listaProductos);
    }

    public HashMap<String, Producto> getListaProductos() {
        return listaProductos;
    }

    public void addList(){
        texto_buscador.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTabla(coincidencia());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTabla(coincidencia());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateTabla(coincidencia());
            }
        });
        tabla_productos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                updateCambiarHabilitado();
            }
        });


    }

    private void updateCambiarHabilitado() {
        if (tabla_productos.getSelectedRow() != -1) {
            Producto p = listaProductos.get(model.getValueAt(tabla_productos.getSelectedRow(),1).toString());
            cambiar_visibilidad_producto.setText(p.isVisible() ? "Deshabilitar" : "Habilitar");
            cambiar_visibilidad_producto.setEnabled(true);
            modificar_producto.setEnabled(true);
        }
    }
    public HashMap<String, Producto> coincidencia () {
        HashMap<String, Producto> map = new HashMap<>();
        for (Producto p : listaProductos.values()) {
            if (String.valueOf(p.getNombreP()).contains(texto_buscador.getText().toUpperCase())) {
                map.put(p.getNombreP(),p);
            }
        }
        return map;
    }

    public void updateTabla(HashMap<String, Producto> localMap) {
        model = (DefaultTableModel) tabla_productos.getModel();
        /** LIMPIAR TABLA*/
        while (model.getRowCount()>0){
            model.removeRow(0);
        }
        /** CARGAR  TABLA*/
        for (Producto p: localMap.values()){
            model.addRow(new Object[]{p.getCodigoP(),p.getNombreP().toUpperCase(),p.getCategoriaP(),p.getPrecioP(),p.getStockP(),p.getStockMinimoP(),(p.isVisible()) ? "True" : "False"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        agregar_producto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texto_buscador = new javax.swing.JTextField();
        boton_salir = new javax.swing.JButton();
        cambiar_visibilidad_producto = new javax.swing.JButton();
        modificar_producto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(800, 520));

        agregar_producto.setText("Agregar");
        agregar_producto.setPreferredSize(new java.awt.Dimension(130, 23));
        agregar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_productoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Buscador:");

        boton_salir.setText("Salir");
        boton_salir.setPreferredSize(new java.awt.Dimension(130, 23));
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        cambiar_visibilidad_producto.setText("Habilitar");
        cambiar_visibilidad_producto.setPreferredSize(new java.awt.Dimension(130, 23));
        cambiar_visibilidad_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar_visibilidad_productoActionPerformed(evt);
            }
        });

        modificar_producto.setText("Modificar");
        modificar_producto.setPreferredSize(new java.awt.Dimension(130, 23));
        modificar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_productoActionPerformed(evt);
            }
        });

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Categoria", "Precio", "Stock", "Stock Minimo", "Habilitado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_productos);
        if (tabla_productos.getColumnModel().getColumnCount() > 0) {
            tabla_productos.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Gestion de Productos");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cambiar_visibilidad_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(texto_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 233, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                    .addContainerGap(18, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cambiar_visibilidad_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        agregar_producto.getAccessibleContext().setAccessibleName("");
        boton_salir.getAccessibleContext().setAccessibleName("");
        cambiar_visibilidad_producto.getAccessibleContext().setAccessibleName("");
        modificar_producto.getAccessibleContext().setAccessibleName("");

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_productoActionPerformed
        // TODO add your handling code here:

        if (tabla_productos.getSelectedRow() != -1) {
            Producto p = listaProductos.get(model.getValueAt(tabla_productos.getSelectedRow(),1).toString());
            ModificarProducto mp = new ModificarProducto(p,this);
            disableButtons();
            mp.setVisible(true);
        }

        //ManagerProducto.actualizarProducto
    }//GEN-LAST:event_modificar_productoActionPerformed

    private void cambiar_visibilidad_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar_visibilidad_productoActionPerformed
        // TODO add your handling code here:

        if (tabla_productos.getSelectedRow() != -1) {
            Producto p = listaProductos.get(model.getValueAt(tabla_productos.getSelectedRow(),1).toString());
            p.setVisible(!p.isVisible());
            ManagerProducto.updateProducto(p);
            cambiar_visibilidad_producto.setEnabled(false);
            modificar_producto.setEnabled(false);
            updateProductos();
        }
    }//GEN-LAST:event_cambiar_visibilidad_productoActionPerformed

    private void agregar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_productoActionPerformed
        AgregarProducto ap = new AgregarProducto(this);
        disableButtons();
        ap.setVisible(true);
        //ManagerProducto.agregarProducto
    }//GEN-LAST:event_agregar_productoActionPerformed

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        // TODO add your handling code here:
        MenuAdministrador ma = new MenuAdministrador(this.user);
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABM_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABM_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABM_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABM_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABM_Producto("").setVisible(true);
            }
        });
    }
    
    public String getUsername() {
        return user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_producto;
    private javax.swing.JButton boton_salir;
    private javax.swing.JButton cambiar_visibilidad_producto;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar_producto;
    private javax.swing.JTable tabla_productos;
    private javax.swing.JTextField texto_buscador;
    // End of variables declaration//GEN-END:variables
}
