/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_graficas.AltaPedido;

/**
 *
 * @author Cell9870
 */
public class AltaPedido_Preview extends javax.swing.JPanel {

    /**
     * Creates new form AltaPedido_Preview
     */
    public AltaPedido_Preview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        LblPedidoCodigo = new javax.swing.JLabel();
        LblNombreAdmin = new javax.swing.JLabel();
        LblNameProv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LblDNIAdmin = new javax.swing.JLabel();
        LblTelAdmin = new javax.swing.JLabel();
        LblCUITProv = new javax.swing.JLabel();
        LblEmailProv = new javax.swing.JLabel();
        LblDirProv = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRenglones = new javax.swing.JTable();
        BtnCrear = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));

        LblPedidoCodigo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblPedidoCodigo.setText("Preview Pedido #xxxx");

        LblNombreAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblNombreAdmin.setText("<nameAdmin>");

        LblNameProv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblNameProv.setText("<nameProveedor>");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        LblDNIAdmin.setText("DNI");

        LblTelAdmin.setText("Teléfono");

        LblCUITProv.setText("CUIT");

        LblEmailProv.setText("Email");

        LblDirProv.setText("Direccion");

        TblRenglones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "U. Medida", "Precio Unitario", "% Bonif", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblRenglones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblRenglones);
        if (TblRenglones.getColumnModel().getColumnCount() > 0) {
            TblRenglones.getColumnModel().getColumn(0).setPreferredWidth(10);
            TblRenglones.getColumnModel().getColumn(1).setPreferredWidth(20);
            TblRenglones.getColumnModel().getColumn(2).setPreferredWidth(10);
            TblRenglones.getColumnModel().getColumn(3).setPreferredWidth(15);
            TblRenglones.getColumnModel().getColumn(4).setPreferredWidth(10);
            TblRenglones.getColumnModel().getColumn(5).setPreferredWidth(5);
            TblRenglones.getColumnModel().getColumn(6).setPreferredWidth(15);
        }

        BtnCrear.setText("Crear Pedido");

        BtnVolver.setText("Volver Atrás");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblNombreAdmin)
                                    .addComponent(LblDNIAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblTelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(133, 133, 133)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(LblNameProv))
                                    .addComponent(LblCUITProv, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblEmailProv, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblDirProv, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(LblPedidoCodigo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addComponent(BtnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnCrear)))))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LblPedidoCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(LblNombreAdmin)
                        .addGap(6, 6, 6)
                        .addComponent(LblDNIAdmin)
                        .addGap(6, 6, 6)
                        .addComponent(LblTelAdmin))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(LblNameProv)
                        .addGap(6, 6, 6)
                        .addComponent(LblCUITProv)
                        .addGap(6, 6, 6)
                        .addComponent(LblEmailProv)
                        .addGap(6, 6, 6)
                        .addComponent(LblDirProv)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrear)
                    .addComponent(BtnVolver))
                .addContainerGap())
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblCUITProv;
    private javax.swing.JLabel LblDNIAdmin;
    private javax.swing.JLabel LblDirProv;
    private javax.swing.JLabel LblEmailProv;
    private javax.swing.JLabel LblNameProv;
    private javax.swing.JLabel LblNombreAdmin;
    private javax.swing.JLabel LblPedidoCodigo;
    private javax.swing.JLabel LblTelAdmin;
    private javax.swing.JTable TblRenglones;
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
