/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_graficas.AltaPedido;

import logica.managers.ManagerPedido;
import objects.Administrador;
import objects.Pedido;
import objects.Proveedor;
import objects.RenglonPedido;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Cell9870
 */
public class AltaPedido_Preview extends javax.swing.JFrame {

    private Map<String, RenglonPedido> mapRenglones = new HashMap<>();
    private Proveedor proveedor;
    private Administrador admin;
    private DefaultTableModel model;
    private AltaPedido_Generador generadorPedido;
    
    public AltaPedido_Preview(AltaPedido_Generador generadorPedido) {
        initComponents();
        this.generadorPedido = generadorPedido;
        this.mapRenglones = generadorPedido.getRenglones();
        this.proveedor = generadorPedido.getProveedor();
        this.admin = generadorPedido.getAdministrador();
        updateText();
        updateTable();
    }

    
    private void updateText() {
        LblPedidoCodigo.setText("Preview Pedido #"+ManagerPedido.generarKey());
        LblNameProv.setText(proveedor.getNombre());
        LblCUITProv.setText("CUIT: "+proveedor.getCuit());
        LblEmailProv.setText("Email: "+proveedor.getEmail());
        LblDirProv.setText("Domicilio: "+proveedor.getDireccion());
        LblNombreAdmin.setText(admin.getApellido()+" "+admin.getNombre());
        LblDNIAdmin.setText("DNI: "+admin.getDni());
        LblTelAdmin.setText("Telefono: "+admin.getTelefono());
    }
    
    private void updateTable() {
        model = (DefaultTableModel) TblRenglones.getModel();
        while(model.getRowCount() > 0) {
            model.removeRow(0);
        }
        for (RenglonPedido rp: mapRenglones.values()) {
            model.addRow(new Object[]{rp.getProducto().getCodigoP(),rp.getProducto().getNombreP(), rp.getCantidad(), rp.getTipoCantidad(), rp.getProducto().getPrecioP(), rp.getDescuento(), rp.getMontoTotal()});
        }
        float value = 0;
        for (RenglonPedido rp: mapRenglones.values()) {
            value += rp.getMontoTotal();
        }
        FldMontoFinal.setText(Float.toString(value));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        LblPedidoCodigo = new javax.swing.JLabel();
        LblNombreAdmin = new javax.swing.JLabel();
        LblNameProv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        LblDNIAdmin = new javax.swing.JLabel();
        LblTelAdmin = new javax.swing.JLabel();
        LblCUITProv = new javax.swing.JLabel();
        LblEmailProv = new javax.swing.JLabel();
        LblDirProv = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblRenglones = new javax.swing.JTable();
        BtnCrear = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FldMontoFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));

        LblPedidoCodigo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblPedidoCodigo.setText("Preview Pedido #xxxx");

        LblNombreAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblNombreAdmin.setText("<nameAdmin>");

        LblNameProv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LblNameProv.setText("<nameProveedor>");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        LblDNIAdmin.setText("DNI");

        LblTelAdmin.setText("Teléfono");

        LblCUITProv.setText("CUIT");

        LblEmailProv.setText("Email");

        LblDirProv.setText("Direccion");

        TblRenglones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "U. Medida", "Precio Unitario", "% Bonif", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblRenglones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TblRenglones);

        BtnCrear.setText("Crear Pedido");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });

        BtnVolver.setText("Volver Atrás");
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        jLabel1.setText("Monto Final:");

        FldMontoFinal.setEditable(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblNombreAdmin)
                                    .addComponent(LblDNIAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblTelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(133, 133, 133)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(LblNameProv))
                                    .addComponent(LblCUITProv, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblEmailProv, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblDirProv, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(283, 283, 283)
                                .addComponent(LblPedidoCodigo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addComponent(BtnVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FldMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(BtnCrear)))))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LblPedidoCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(LblNombreAdmin)
                        .addGap(6, 6, 6)
                        .addComponent(LblDNIAdmin)
                        .addGap(6, 6, 6)
                        .addComponent(LblTelAdmin))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(LblNameProv)
                        .addGap(6, 6, 6)
                        .addComponent(LblCUITProv)
                        .addGap(6, 6, 6)
                        .addComponent(LblEmailProv)
                        .addGap(6, 6, 6)
                        .addComponent(LblDirProv)))
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrear)
                    .addComponent(BtnVolver)
                    .addComponent(jLabel1)
                    .addComponent(FldMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        if (JOptionPane.showOptionDialog(content, "¿Está seguro que desea cargar este pedido?",
                    "Confirmación de Alta de Pedido", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, 
                    null, null, null) == 0) {
        
            Pedido pedido = new Pedido(
                ManagerPedido.generarKey(),
                admin,
                proveedor
            );

            ManagerPedido.cargarPedido(pedido, mapRenglones.values());
            JOptionPane.showMessageDialog(content, "El pedido fue cargado en el sistema","Alta de Pedido exitosa",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            generadorPedido.setVisible(true);
            
            this.dispose();
        }        
    }//GEN-LAST:event_BtnCrearActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        this.setVisible(false);
        generadorPedido.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaPedido_Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaPedido_Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaPedido_Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaPedido_Preview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaPedido_Preview(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JTextField FldMontoFinal;
    private javax.swing.JLabel LblCUITProv;
    private javax.swing.JLabel LblDNIAdmin;
    private javax.swing.JLabel LblDirProv;
    private javax.swing.JLabel LblEmailProv;
    private javax.swing.JLabel LblNameProv;
    private javax.swing.JLabel LblNombreAdmin;
    private javax.swing.JLabel LblPedidoCodigo;
    private javax.swing.JLabel LblTelAdmin;
    private javax.swing.JTable TblRenglones;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
